# Generated by Django 4.0 on 2022-01-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todolist_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2022-01-07'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='dueDate',
            field=models.DateField(default='2022-01-07'),
        ),
    ]
